##### Lehrstuhl für Analytics and Statistics (IOR)
##### Prof. Dr. Oliver Grothe
##### SoSe 25

# Analyse multivariater Daten
## Übung 6

Betrachten Sie wieder den StatStud Datensatz (Ilias), betrachten Sie jedoch
ausschließlich männliche Studenten.

In [7]:
import pandas as pd
import numpy as np
from scipy.stats import t
import seaborn as sns
import matplotlib.pyplot as plt
data=pd.read_csv('statstud.csv', sep=';',header=None)
data_m=data.loc[data.iloc[:,3]==2]
data_m.head()

     0     1     2   3   4   5    6    7   8   9    10  11   12
1   190  45.0  87.0   2   6  83  4.0  3.7   0   1  0.0   1  5.0
3   179  42.5  80.0   2   6  85  3.0  2.0   1   1  0.0   1  5.0
5   186  44.0  76.0   2   2  89  2.7  1.7   1   0  0.0   0  5.0
6   187  46.0  70.0   2   6  88  2.0  2.6   0   0  0.0   0  3.0
11  180  44.0  73.0   2   9  87  1.7  2.0   0   0  0.0   1  8.0

Bilden Sie die emprische Korrelationsmatrix der Merkmale Größe, Schuhgröße und
Gewicht.

In [8]:

corr=data_m.loc[:,:2].corr()
corr

          0         1         2
0  1.000000  0.644661  0.482863
1  0.644661  1.000000  0.370977
2  0.482863  0.370977  1.000000

Testen Sie die Merkmale Gewicht und Schuhgröße zum 5%-Niveau auf Unkorreliertheit.

H0 : ρ = 0 und H1 : ρ != 0

In [9]:
t_stat=(corr.loc[1,2]*np.sqrt(np.size(data_m,axis=0)-2))/(np.sqrt(1-corr.loc[1,2]**2))
t_stat

3.413189141822429

In [10]:
p_value=1-t.cdf(t_stat,df=np.size(data_m,axis=0)-2)
print(p_value)

0.0005254101353989737

In [11]:
krit=[t.ppf(0.025,df=np.size(data_m,axis=0)-2),t.ppf(0.975,df=np.size(data_m,axis=0)-2)]
krit

[-1.9929971255321668, 1.9929971255321663]

In [12]:
if t_stat> krit[1] or  t_stat< krit[0]:
    print('H0 wird abgelehnt!')

H0 wird abgelehnt!

Ermitteln sie einen Sch¨atzer fur die partielle Korrelation von  Gewicht und Schuhgröße
unter der Partialisierung von Größe und interpretieren Sie Ihr Ergebnis.

In [13]:
p_part=(corr.loc[1,2]-corr.loc[0,1]*corr.loc[0,2])/np.sqrt((1-corr.loc[0,1]**2)*(1-corr.loc[0,2]**2))
print(p_part)

0.08917017435746946