##### Lehrstuhl für Analytics and Statistics (IOR)
##### Prof. Dr. Oliver Grothe
##### SoSe 2025

# Analyse multivariater Daten
## Übung 8

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import t
from numpy import linalg
import scipy
import seaborn as sns
import statsmodels.api as sm
from statsmodels.formula.api import ols
#!pip install seaborn --upgrade
import matplotlib.pyplot as plt
# Plotting
plt.rcParams['figure.figsize'] = [12, 9]
sns.set(style='darkgrid')

# Warnungen unterdrücken
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

## Aufgabe 6
Dateneingabe

In [5]:
late_beard = np.array([[1, 5, 2, 0],
    [2, 6, 4, 0],
    [3, 10, 5, 2],
    [4, 12, 6, 5],
    [1, 15, 4, 3],
    [0, 7, 3, 4],
    [3, 8, 2, 2],
    [0, 2, 3, 1],
    [2, 10, 1, 1],
    [1, 5, 0, 2]])
df=pd.DataFrame(late_beard,columns=['Voll','Dreitage','Oberlippe','Ohne'])
df

   Voll  Dreitage  Oberlippe  Ohne
0     1         5          2     0
1     2         6          4     0
2     3        10          5     2
3     4        12          6     5
4     1        15          4     3
5     0         7          3     4
6     3         8          2     2
7     0         2          3     1
8     2        10          1     1
9     1         5          0     2

In [19]:
# reshape the d dataframe suitable for statsmodels package 
df_melt = pd.melt(df.reset_index(), id_vars=['index'], value_vars=['Voll', 'Dreitage', 'Oberlippe', 'Ohne'])
# replace column names
df_melt.columns = ['index', 'beardtype', 'value']

import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['Voll'], df['Dreitage'], df['Oberlippe'], df['Ohne'])
print(fvalue, pvalue)


# get ANOVA table as R like output
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Ordinary Least Squares (OLS) model
model = ols('value ~ C(beardtype)', data=df_melt).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
anova_table

15.35922810489857 1.3479617458583985e-06

               sum_sq    df          F    PR(>F)
C(beardtype)  258.675   3.0  15.359228  0.000001
Residual      202.100  36.0        NaN       NaN

p Wert < 0.05 ist signifikant. Daher signifikanter Unterschiede zwischen den Bartträgern.

## Aufgabe 7
Bestimmen Sie Eigenwerte und Eigenvektoren der Matrix $A$

In [15]:
A=np.array([[3,-1,-1],[-1,3,1],[-1,1,5]])
A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [-1,  1,  5]])

In [18]:
ew,ev = linalg.eig(A)

In [19]:
ew

array([6., 2., 3.])

In [20]:
ev

array([[-4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
       [ 4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [ 8.16496581e-01, -1.27652686e-16,  5.77350269e-01]])

In [26]:
B=np.dot(ev.T,A)

In [27]:
np.dot(B,ev)

array([[ 6.00000000e+00,  1.59507816e-15,  1.23742931e-15],
       [ 1.31427776e-15,  2.00000000e+00, -4.10823025e-16],
       [ 9.15855623e-16, -6.65190147e-16,  3.00000000e+00]])